language: node_js
node_js:
  - "4"
  - "6"
  - "7"

branches:
  only:
    - master

before_script:
  - npm install grunt-cli

after_script:
  - npm run coveralls

notifications:
  webhooks: http://travalizit.org/builds
